### PR TITLE
add new feature to auto copy function protoype from  c file from spec…

### PR DESCRIPTION
**Pull request by be-great**
Usage: alxcheck -D <dir_name> -H <header_name>.h

Example: alxcheck -D . -H main.h

This command will check all prototypes in the specified directory for C files. 🕵️‍♂️

Requirements:-
- Install ctags: sudo apt-get install exuberant-ctags 🛠️
- Ensure correct function prototypes in C files; for example, the open bracket should be in Betty style on a different line:
  Example: `int function(void){}` ❌ | `int function(void)` and the bracket on a new line ✔

Screenshot from 2023-11-23 19-27-38

Screenshot from 2023-11-23 19-28-06

### CODE REVIEW

**Comment by adobki** [comment]
Hello, @be-great. First of all, well done! Month three in ALX SE and already making significant pull requests! Fantastic! Can't wait to see what you'd be doing at month nine, at graduation, and even beyond! 😎

The feature you're proposing is great, but I think it needs some major tweaks to properly align with the project:
1. Your code hijacks the functionality of the entire program, preventing all the existing code from being accessed once invoked. It needs better integration.
2. The `autoproto` function needs to be moved from `main.py` to align with the project's code/file structure.
3. Finally, and more as a suggestion, your proposed feature ***fixes*** without actually performing any ***checks***, even though the project is aptly named *alx**check***. So how about making your code a checker instead, invoked on C files by default, then have the `-d/-h` switches invoke automatic fixes if the check fails? What do you think?

*(__DISCLAIMER:__ I'm just a collaborator, not the project owner or even a major stakeholder.)*

**Comment by be-great** [comment]
Hello @adobki 🚀
          @Emmo00 🚀

Thank you for your valuable feedback! 💪 I've made the suggested adjustments to my code and am eager to receive your approval. Please take your time to review, and if there are any further suggestions or changes you'd like, I'm more than happy to address them.

Looking forward to your response! 🌟

**Comment by Emmo00** [comment]
Hey @be-great ... Thanks for your PR.
Sorry I've not been able to review it, I've been busy with some things



Thank you @adobki ... Nice insights

**Comment by adobki** [comment]
> Please take your time to review, and if there are any further suggestions or changes you'd like, I'm more than happy to address them.

Hello, @be-great 
Glad I could be of help. Sorry I've been #AWOL. Have a lot of projects I'm working on at the moment.
Wow, well done! I'd do this as soon as I can and let to you know. Thanks.👍

@Emmo00 , don't mention it, bro. I'm always happy to be of help. I see you've been choked-up by all dem projects as well. Less than a month now for us to be done here, and then it's on to the next one! Cheers! 😉 #doHardThings

**Comment by be-great** [comment]
what happens ?!

**Comment by Emmo00** [comment]
Hey @be-great 

I'm sorry I'm just saying this, but this feature is kinda out of the scope of the project

If you're willing, you can create a new repo and I'll gladly contribute to implement this feature 

Don't be mad 🥹, I really appreciate your efforts. Thanks 🙏

**Comment by be-great** [comment]
No problem. Thanks for your feedback and time  :)

**Comment by Emmo00** [comment]
Are you moving forward to build it?

**Comment by be-great** [comment]
> Are you moving forward to build it? 


Certainly, I just need some time to organize it. 🙌

**Pull request closed without merging**
